jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Install Go
      if: success()
      uses: actions/setup-go@v4
      with:
        go-version: "1.21"
    - name: Set environment variables
      run: |
        echo "GOPATH=${{ runner.workspace }}" >> $GITHUB_ENV
        echo "${{ runner.workspace }}/bin" >> $GITHUB_PATH
      shell: bash
    - name: Setup XGO
      run: go install github.com/crazy-max/xgo@latest
    - name: Run dist
      run: make dist
    - name: Upload Asset to Release with a wildcard
      uses: AButler/upload-release-assets@v2.0
      with:
        files: dist/*.zip
        repo-token: ${{ secrets.GITHUB_TOKEN }}
name: Release upload
"on":
  release:
    types:
    - published
